// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUSQ4yTkJHZ7GZRZvoQt9vhXYfiVIfPko',
    appId: '1:28250213611:web:57f44868e98d164dce02ae',
    messagingSenderId: '28250213611',
    projectId: 'hackaholic-a793a',
    authDomain: 'hackaholic-a793a.firebaseapp.com',
    storageBucket: 'hackaholic-a793a.appspot.com',
    measurementId: 'G-BE9D02RFKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHD09Bni5Nv2MGtu8zjOnZX0P64G6xFLY',
    appId: '1:28250213611:android:cc44dfe2b45c7bbace02ae',
    messagingSenderId: '28250213611',
    projectId: 'hackaholic-a793a',
    storageBucket: 'hackaholic-a793a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmw3bZY-OdludQyNsKyLSY1D7oebD35MM',
    appId: '1:28250213611:ios:b888f4e8eb93a926ce02ae',
    messagingSenderId: '28250213611',
    projectId: 'hackaholic-a793a',
    storageBucket: 'hackaholic-a793a.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmw3bZY-OdludQyNsKyLSY1D7oebD35MM',
    appId: '1:28250213611:ios:478598c2f60b3799ce02ae',
    messagingSenderId: '28250213611',
    projectId: 'hackaholic-a793a',
    storageBucket: 'hackaholic-a793a.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
